package com.wpsnetwork.entidades.unoauno;
// Generated 10-mar-2016 12:20:33 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Direcciones generated by hbm2java
 */
@Entity
@Table(name = "DIRECCIONES")
public class Direccion implements java.io.Serializable {

	private BigDecimal id;
	private String calle;
	private String codigopostal;

	public Direccion() {
	}

	public Direccion(BigDecimal id) {
		this.id = id;
	}

	public Direccion(BigDecimal id, String calle, String codigopostal ) {
		this.id = id;
		this.calle = calle;
		this.codigopostal = codigopostal;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "CALLE", length = 50)
	public String getCalle() {
		return this.calle;
	}

	public void setCalle(String calle) {
		this.calle = calle;
	}

	@Column(name = "CODIGOPOSTAL", length = 50)
	public String getCodigopostal() {
		return this.codigopostal;
	}

	public void setCodigopostal(String codigopostal) {
		this.codigopostal = codigopostal;
	}

}
