package com.wpsnetwork.entidades.unoauno;
// Generated 10-mar-2016 12:20:33 by Hibernate Tools 4.0.0

import java.math.BigDecimal;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Personas generated by hbm2java
 */
@Entity
@Table(name = "PERSONAS")
public class Persona implements java.io.Serializable {

	private BigDecimal id;
	private Direccion direccion;
	private String nombre;

	public Persona() {
	}

	public Persona(BigDecimal id) {
		this.id = id;
	}

	public Persona(BigDecimal id, Direccion direcciones, String nombre) {
		this.id = id;
		this.direccion = direcciones;
		this.nombre = nombre;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

//	esto es lo que me ha escrito hibernate por defecto, lo hemos quietado
//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "DIRECCION")
	
	@OneToOne(cascade={CascadeType.PERSIST, CascadeType.REMOVE})
	@JoinColumn(name="DIRECCION")
	public Direccion getDireccion() {
		return this.direccion;
	}

	public void setDireccion(Direccion direccion) {
		this.direccion = direccion;
	}

	@Column(name = "NOMBRE", length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Override
	public String toString() {
		return "Persona [" + (id != null ? "id=" + id + ", " : "")
				+ (direccion != null ? "direcciones=" + direccion + ", " : "")
				+ (nombre != null ? "nombre=" + nombre : "") + "]";
	}

	
	
}
