package com.wpsnetwork.entidades;
// Generated 07-mar-2016 12:11:42 by Hibernate Tools 4.0.0

import java.time.LocalDate;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Pedido generated by hbm2java
 */
@Entity
@Table (name="PEDIDO")

public class Pedido implements java.io.Serializable {

	private int id;
	private Cliente cliente;
	private LocalDate fecha;
	private String info;

	public Pedido() {
	}

	public Pedido(int id, Cliente cliente, LocalDate fecha, String info) {
		this.id = id;
		this.cliente = cliente;
		this.fecha = fecha;
		this.info = info;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE , generator = "pedido_seq")
	@SequenceGenerator(name="pedido_seq", sequenceName="PEDIDO_ID_SQL", allocationSize=1) // no nos esta pillando la secuencia bien y marc no sabe donde puede estar fallando
	@Column(name="ID") 
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch=FetchType.EAGER)
	@JoinColumn(name="IDCLIENTE", nullable=false)
	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

    @Column(name="fecha")
	public LocalDate getFecha() {
		return this.fecha;
	}

	public void setFecha(LocalDate fecha) {
		this.fecha = fecha;
	}

    @Column(name="info")
	public String getInfo() {
		return this.info;
	}

	public void setInfo(String info) {
		this.info = info;
	}

	@Override
	public String toString() {
		return "Pedido [id=" + id + ", " + (fecha != null ? "fecha=" + fecha + ", " : "")
				+ (info != null ? "info=" + info : "") + "]";
	}

	
}
