package com.wpsnetwork.entidades;
// Generated 07-mar-2016 12:11:42 by Hibernate Tools 4.0.0

import java.time.LocalDate;

/**
 * Pedido generated by hbm2java
 */
public class Pedido implements java.io.Serializable {

	private int id;
	private Cliente cliente;
	private LocalDate fecha;
	private String info;

	public Pedido() {
	}

	public Pedido(int id, Cliente cliente, LocalDate fecha, String info) {
		this.id = id;
		this.cliente = cliente;
		this.fecha = fecha;
		this.info = info;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public LocalDate getFecha() {
		return this.fecha;
	}

	public void setFecha(LocalDate fecha) {
		this.fecha = fecha;
	}

	public String getInfo() {
		return this.info;
	}

	public void setInfo(String info) {
		this.info = info;
	}

	@Override
	public String toString() {
		return "Pedido [id=" + id + ", " + (fecha != null ? "fecha=" + fecha + ", " : "")
				+ (info != null ? "info=" + info : "") + "]";
	}

	
}
